config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :shows

   root 'shows#index'

end

app/models/show.rb
class Show < ActiveRecord::Base
	belongs_to :user
	def getEpisodeList
		self.name

		response = HTTParty.get(URI.encode("http://api.tvmaze.com/singlesearch/shows?q=\"#{self.name}\""))

		id = response["id"]

		episodes = HTTParty.get(URI.encode("http://api.tvmaze.com/shows/#{id}/episodes"))

		episode_list = Array.new
		
		episodes.each do |episode|
			episode_data = Hash.new

			episode_data["season_number"] = episode["season"]
			episode_data["episode_number"] = episode["number"]
			episode_data["episode_name"]  = episode["name"]
			episode_data["episode_airdate"] = episode["airdate"]

			episode_list.push episode_data
		end 
		
		return episode_list
	end

	def getShowInfo
		

		response = HTTParty.get(URI.encode("http://api.tvmaze.com/singlesearch/shows?q=\"#{self.name}\""))

		id = response["id"]

		episodes = HTTParty.get(URI.encode("http://api.tvmaze.com/shows/#{id}/episodes"))

		show_info = Hash.new
		show_info["name"] = response["name"]
		show_info["image"] = response["image"]["medium"]
		show_info["episodes"] = Array.new
		
		episodes.each do |episode|
			episode_data = Hash.new

			episode_data["season_number"] = episode["season"]
			episode_data["episode_number"] = episode["number"]
			episode_data["episode_name"]  = episode["name"]
			episode_data["episode_airdate"] = episode["airdate"]

			episode = episode_data["episode_number"].to_s.length == 1 ? "0#{episode_data["episode_number"]}" : episode_data["episode_number"]
			season = episode_data["season_number"].to_s.length == 1 ? "0#{episode_data["season_number"]}" : episode_data["season_number"]

			episode_data["torrent_search"] = URI::encode("https://thepiratebay.org/search/#{self.name.tr("'","")} s#{season}e#{episode}")
			episode_data["subtitle_search"] = "http://www.tusubtitulo.com/showsub.php?ushow=#{self.name.downcase.tr(" ", "-").tr("'","")}&useason=#{season}&uepisode=#{episode}"

			show_info["episodes"].push episode_data
		end 
		
		show_info["episodes"].select! {|episode| episode["season_number"] >= self.last_season_number and episode["episode_number"] >= self.last_episode_number}
		return show_info
	end

	def getName
		response = HTTParty.get(URI.encode("http://api.tvmaze.com/singlesearch/shows?q=\"#{self.name}\""))

		response["name"]
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def main_index

    @show_list = Array.new

    @shows = Show.all
    @shows.each do |show|
      @show_list.push show.getShowInfo
    end

    return @show_list
  end

  # GET /shows
  # GET /shows.json
  def index
    @shows = current_user.shows
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show_info = @show.getShowInfo
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)
    name = @show.getName
    @show.name = name
    @show.user_id = current_user.id

    @show.last_episode_number = 1
    @show.last_season_number = 1

    respond_to do |format|
      if !@show.name.nil? && @show.save
        format.html { redirect_to root_url, notice: "Serie agregada correctamente." }
        format.json { render :show, status: :created, location: @show }
      else
        flash[:notice] = 'Nombre de serie incorrecto.'
        format.html { render :new}
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    logger.debug "#{show_params.inspect}"
    respond_to do |format|
      if @show.update(show_params)
        format.html { render :edit, notice: 'Show was successfully updated.' }
        format.json { render json: @show.getEpisodeList, status: :ok  }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Serie borrada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:name, :last_episode_number, :last_season_number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
	<title>Recordador de Series</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Aceptar"%>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".sidebar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Series</a>
      </div>
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li><%= link_to('Cerrar Sesión', destroy_user_session_path, :method => :delete)%></li>
        </ul>

        <ul class="nav nav-sidebar">
          <li class="active"><%= link_to('Nueva Serie', new_show_path) %></a></li>
        </ul>

        <ul class="nav nav-sidebar">
          <% current_user.shows.each do |show| %>
          <li><a class="menu-item" data-id="<%= show.id %>"><%= show.name %></a></li>
          <% end %>
        </ul>

      </div>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class ="show-container"></div>
    </div>
  </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="./Dashboard Template for Bootstrap_files/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
        <script src="./Dashboard Template for Bootstrap_files/bootstrap.min.js"></script>
        <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
        <script src="./Dashboard Template for Bootstrap_files/holder.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="./Dashboard Template for Bootstrap_files/ie10-viewport-bug-workaround.js"></script>

app/views/shows/main_index.html.erb
<% @show_list.each do |show| %>
  <div>
    <%= image_tag(show["image"], size: "50x50")%>
    <%= show["name"] %>
  </div>

  <table>
    <thead>
      <tr>
        <th>Season Number</th>
        <th>Episode Number</th>
        <th>Name</th>
        <th>Airdate</th>
      </tr>
    </thead>

    <tbody>
      <% show["episodes"].each do |episode| %>
        <tr> 
          <td><%= episode["season_number"] %></td>
          <td><%= episode["episode_number"] %></td>
          <td><%= episode["episode_name"] %></td>
          <td><%= episode["episode_airdate"] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'New Show', new_show_path %>


app/views/shows/new.html.erb
 <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
 <% end %>

<h1>Nueva Serie</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row show-head">
    <div class="col-md-4">
      <img alt="Bootstrap Image Preview" src='<%= @show_info["image"] %>' class="img-circle" height="150" width="150"/>
    </div>
    <div class="col-md-4">
      <h2>
        <%= @show.name %>
      </h2>
      <div id="id" hidden="true"><%= @show.id %></div>
    </div>
    <div class="col-md-4">
     <div class="checkbox">
       <label><input id="enable_selection" type="checkbox" value="">Habilitar selección</label>
     </div>
     <button type="button" class="btn btn-default" id="reset">Reiniciar</button> 
     <%= link_to('Borrar', show_path, method: :delete , :class => 'btn btn-default') %>
   </div>
 </div>
 <div class="row show-body">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped" id="data">
        <thead>
          <tr>
            <th>Temporada</th>
            <th>Episodio</th>
            <th>Nombre</th>
            <th>Fecha de emisión</th>
            <th>Torrent</th>
            <th>Subtítulo</th>
          </tr>
        </thead>
        <tbody>
          <% @show_info["episodes"].each do |episode| %>
          <tr> 
            <td><%= episode["season_number"] %></td>
            <td><%= episode["episode_number"] %></td>
            <td><%= episode["episode_name"] %></td>
            <td><%= episode["episode_airdate"] %></td>
            <td><%= link_to "buscar torrent", "#{episode["torrent_search"]}", :target => "_blank" %></td>
            <td><%= link_to "buscar subtitulo", "#{episode["subtitle_search"]}", :target => "_blank" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>